#!/bin/sh
cd "$(dirname "$0")"
g++ -std=c++17 \
    -I "../FTXUI/include" \
    -I "../FTXUI/src" \
    ../FTXUI/src/ftxui/dom/automerge.cpp \
    ../FTXUI/src/ftxui/dom/blink.cpp \
    ../FTXUI/src/ftxui/dom/bold.cpp \
    ../FTXUI/src/ftxui/dom/border.cpp \
    ../FTXUI/src/ftxui/dom/box_helper.cpp \
    ../FTXUI/src/ftxui/dom/canvas.cpp \
    ../FTXUI/src/ftxui/dom/clear_under.cpp \
    ../FTXUI/src/ftxui/dom/color.cpp \
    ../FTXUI/src/ftxui/dom/composite_decorator.cpp \
    ../FTXUI/src/ftxui/dom/dbox.cpp \
    ../FTXUI/src/ftxui/dom/dim.cpp \
    ../FTXUI/src/ftxui/dom/flex.cpp \
    ../FTXUI/src/ftxui/dom/flexbox.cpp \
    ../FTXUI/src/ftxui/dom/flexbox_config.cpp \
    ../FTXUI/src/ftxui/dom/flexbox_helper.cpp \
    ../FTXUI/src/ftxui/dom/focus.cpp \
    ../FTXUI/src/ftxui/dom/frame.cpp \
    ../FTXUI/src/ftxui/dom/gauge.cpp \
    ../FTXUI/src/ftxui/dom/graph.cpp \
    ../FTXUI/src/ftxui/dom/gridbox.cpp \
    ../FTXUI/src/ftxui/dom/hbox.cpp \
    ../FTXUI/src/ftxui/dom/hyperlink.cpp \
    ../FTXUI/src/ftxui/dom/inverted.cpp \
    ../FTXUI/src/ftxui/dom/italic.cpp \
    ../FTXUI/src/ftxui/dom/linear_gradient.cpp \
    ../FTXUI/src/ftxui/dom/node.cpp \
    ../FTXUI/src/ftxui/dom/node_decorator.cpp \
    ../FTXUI/src/ftxui/dom/paragraph.cpp \
    ../FTXUI/src/ftxui/dom/reflect.cpp \
    ../FTXUI/src/ftxui/dom/scroll_indicator.cpp \
    ../FTXUI/src/ftxui/dom/selection.cpp \
    ../FTXUI/src/ftxui/dom/selection_style.cpp \
    ../FTXUI/src/ftxui/dom/separator.cpp \
    ../FTXUI/src/ftxui/dom/size.cpp \
    ../FTXUI/src/ftxui/dom/spinner.cpp \
    ../FTXUI/src/ftxui/dom/strikethrough.cpp \
    ../FTXUI/src/ftxui/dom/table.cpp \
    ../FTXUI/src/ftxui/dom/text.cpp \
    ../FTXUI/src/ftxui/dom/underlined.cpp \
    ../FTXUI/src/ftxui/dom/underlined_double.cpp \
    ../FTXUI/src/ftxui/dom/util.cpp \
    ../FTXUI/src/ftxui/dom/vbox.cpp \
    ../FTXUI/src/ftxui/screen/box.cpp \
    ../FTXUI/src/ftxui/screen/color.cpp \
    ../FTXUI/src/ftxui/screen/color_info.cpp \
    ../FTXUI/src/ftxui/screen/screen.cpp \
    ../FTXUI/src/ftxui/screen/string.cpp \
    ../FTXUI/src/ftxui/screen/surface.cpp \
    ../FTXUI/src/ftxui/screen/terminal.cpp \
    ../FTXUI/src/ftxui/component/app.cpp \
    ../FTXUI/src/ftxui/component/animation.cpp \
    ../FTXUI/src/ftxui/component/button.cpp \
    ../FTXUI/src/ftxui/component/catch_event.cpp \
    ../FTXUI/src/ftxui/component/component.cpp \
    ../FTXUI/src/ftxui/component/component_options.cpp \
    ../FTXUI/src/ftxui/component/container.cpp \
    ../FTXUI/src/ftxui/component/event.cpp \
    ../FTXUI/src/ftxui/component/renderer.cpp \
    ../FTXUI/src/ftxui/component/task.cpp \
    ../FTXUI/src/ftxui/component/task_runner.cpp \
    ../FTXUI/src/ftxui/component/task_queue.cpp \
    ../FTXUI/src/ftxui/component/terminal_input_parser.cpp \
    Navigation.cpp \
    -o nav.exe
